import type { BattleRoundDefinitionData, EnemyKindData, EnemyPrototypeData } from "./data";

export const ENEMY_PROTOTYPES: Record<EnemyKindData, EnemyPrototypeData> = {
  chaser: {
    kind: "chaser",
    radius: 18,
    healthMax: 1,
    moveSpeed: 120,
    contactDamage: 1,
    contactDamageCooldownSeconds: 0.7,
  },
  tank: {
    kind: "tank",
    radius: 25,
    healthMax: 1,
    moveSpeed: 75,
    contactDamage: 2,
    contactDamageCooldownSeconds: 0.9,
  },
  runner: {
    kind: "runner",
    radius: 14,
    healthMax: 1,
    moveSpeed: 185,
    contactDamage: 1,
    contactDamageCooldownSeconds: 0.55,
  },
};

export const DEMO_BATTLE_ROUNDS: BattleRoundDefinitionData[] = [
  {
    roundNumber: 1,
    durationSeconds: 20,
    waveGroups: [
      {
        id: "round-1-edge-swarms",
        triggerAtSeconds: 0,
        repeatCount: 12,
        repeatIntervalSeconds: 1.35,
        spawnDelaySeconds: 0.7,
        batchDelaySeconds: 0.04,
        positionRule: { type: "group", centerRule: { type: "edge", padding: 48 }, radius: 170 },
        units: [{ enemyKind: "chaser", minCount: 4, maxCount: 6, spawnChance: 1 }],
      },
      {
        id: "round-1-center-pressure",
        triggerAtSeconds: 6,
        repeatCount: 5,
        repeatIntervalSeconds: 2.8,
        spawnDelaySeconds: 0.8,
        batchDelaySeconds: 0.05,
        positionRule: { type: "random", margin: 170 },
        units: [{ enemyKind: "chaser", minCount: 2, maxCount: 3, spawnChance: 1 }],
      },
    ],
  },
  {
    roundNumber: 2,
    durationSeconds: 30,
    waveGroups: [
      {
        id: "round-2-chaser-stream",
        triggerAtSeconds: 0,
        repeatCount: 18,
        repeatIntervalSeconds: 1.25,
        spawnDelaySeconds: 0.7,
        batchDelaySeconds: 0.04,
        positionRule: { type: "group", centerRule: { type: "edge", padding: 48 }, radius: 180 },
        units: [{ enemyKind: "chaser", minCount: 5, maxCount: 8, spawnChance: 1 }],
      },
      {
        id: "round-2-tank-pair",
        triggerAtSeconds: 7,
        repeatCount: 5,
        repeatIntervalSeconds: 4.8,
        spawnDelaySeconds: 0.9,
        batchDelaySeconds: 0.08,
        positionRule: { type: "group", centerRule: { type: "edge", padding: 64 }, radius: 120 },
        units: [{ enemyKind: "tank", minCount: 1, maxCount: 2, spawnChance: 1 }],
      },
      {
        id: "round-2-runner-flanks",
        triggerAtSeconds: 11,
        repeatCount: 6,
        repeatIntervalSeconds: 3.2,
        spawnDelaySeconds: 0.8,
        batchDelaySeconds: 0.04,
        positionRule: { type: "group", centerRule: { type: "edge", padding: 48 }, radius: 140 },
        units: [{ enemyKind: "runner", minCount: 2, maxCount: 4, spawnChance: 1 }],
      },
    ],
  },
  {
    roundNumber: 3,
    durationSeconds: 40,
    waveGroups: [
      {
        id: "round-3-mixed-edge",
        triggerAtSeconds: 0,
        repeatCount: 24,
        repeatIntervalSeconds: 1.15,
        spawnDelaySeconds: 0.65,
        batchDelaySeconds: 0.035,
        positionRule: { type: "group", centerRule: { type: "edge", padding: 48 }, radius: 200 },
        units: [
          { enemyKind: "chaser", minCount: 6, maxCount: 9, spawnChance: 1 },
          { enemyKind: "runner", minCount: 2, maxCount: 4, spawnChance: 0.75 },
        ],
      },
      {
        id: "round-3-center-pressure",
        triggerAtSeconds: 8,
        repeatCount: 8,
        repeatIntervalSeconds: 3.8,
        spawnDelaySeconds: 0.8,
        batchDelaySeconds: 0.06,
        positionRule: { type: "random", margin: 140 },
        units: [{ enemyKind: "tank", minCount: 2, maxCount: 3, spawnChance: 1 }],
      },
    ],
  },
  {
    roundNumber: 4,
    durationSeconds: 50,
    waveGroups: [
      {
        id: "round-4-dense-chasers",
        triggerAtSeconds: 0,
        repeatCount: 34,
        repeatIntervalSeconds: 1.05,
        spawnDelaySeconds: 0.6,
        batchDelaySeconds: 0.03,
        positionRule: { type: "group", centerRule: { type: "edge", padding: 48 }, radius: 220 },
        units: [{ enemyKind: "chaser", minCount: 7, maxCount: 11, spawnChance: 1 }],
      },
      {
        id: "round-4-runner-flanks",
        triggerAtSeconds: 5,
        repeatCount: 12,
        repeatIntervalSeconds: 3.1,
        spawnDelaySeconds: 0.7,
        batchDelaySeconds: 0.035,
        positionRule: { type: "group", centerRule: { type: "edge", padding: 48 }, radius: 170 },
        units: [{ enemyKind: "runner", minCount: 4, maxCount: 7, spawnChance: 1 }],
      },
      {
        id: "round-4-center-crush",
        triggerAtSeconds: 10,
        repeatCount: 8,
        repeatIntervalSeconds: 4.4,
        spawnDelaySeconds: 0.85,
        batchDelaySeconds: 0.06,
        positionRule: { type: "random", margin: 140 },
        units: [{ enemyKind: "tank", minCount: 2, maxCount: 4, spawnChance: 1 }],
      },
    ],
  },
  {
    roundNumber: 5,
    durationSeconds: 60,
    waveGroups: [
      {
        id: "round-5-horde-chasers",
        triggerAtSeconds: 0,
        repeatCount: 48,
        repeatIntervalSeconds: 0.9,
        spawnDelaySeconds: 0.55,
        batchDelaySeconds: 0.025,
        positionRule: { type: "group", centerRule: { type: "edge", padding: 48 }, radius: 240 },
        units: [{ enemyKind: "chaser", minCount: 8, maxCount: 12, spawnChance: 1 }],
      },
      {
        id: "round-5-runners",
        triggerAtSeconds: 4,
        repeatCount: 18,
        repeatIntervalSeconds: 2.8,
        spawnDelaySeconds: 0.65,
        batchDelaySeconds: 0.03,
        positionRule: { type: "group", centerRule: { type: "edge", padding: 48 }, radius: 190 },
        units: [{ enemyKind: "runner", minCount: 5, maxCount: 8, spawnChance: 1 }],
      },
      {
        id: "round-5-tanks",
        triggerAtSeconds: 8,
        repeatCount: 12,
        repeatIntervalSeconds: 4.2,
        spawnDelaySeconds: 0.8,
        batchDelaySeconds: 0.055,
        positionRule: { type: "random", margin: 130 },
        units: [{ enemyKind: "tank", minCount: 3, maxCount: 5, spawnChance: 1 }],
      },
    ],
  },
];
